/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversor;

import static java.lang.String.valueOf;
import java.text.DecimalFormat;

/**
 *
 * @author dalonsoperez
 */
public class Convertir extends javax.swing.JFrame {

    double valor;
    DecimalFormat df  = new DecimalFormat("0.00");
    /**
     * Creates new form Convertir
     */
    public Convertir() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        MonedaEntrada1 = new javax.swing.JLabel();
        MonedaSalida1 = new javax.swing.JLabel();
        MonedaEntrada2 = new javax.swing.JLabel();
        MonedaSalida2 = new javax.swing.JLabel();
        Salida1 = new javax.swing.JLabel();
        Salida2 = new javax.swing.JLabel();
        Dinero1 = new javax.swing.JTextField();
        Dinero2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setBackground(new java.awt.Color(255, 0, 0));
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("x");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        Back.setBackground(new java.awt.Color(0, 0, 0));
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("<");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        MonedaEntrada1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(MonedaEntrada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 30));

        MonedaSalida1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(MonedaSalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 150, 30));

        MonedaEntrada2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(MonedaEntrada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, 30));

        MonedaSalida2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(MonedaSalida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 150, 30));

        Salida1.setBackground(new java.awt.Color(255, 255, 255));
        Salida1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Salida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 150, 30));

        Salida2.setBackground(new java.awt.Color(255, 255, 255));
        Salida2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Salida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 150, 30));

        Dinero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Dinero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, 30));

        Dinero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Dinero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, 30));

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 100, -1));

        jButton2.setText("Convertir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 100, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 400, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        valor = Double.parseDouble(Dinero1.getText());
        calcula1(Menu.getSelector());
        Salida1.setText(valueOf(df.format(valor)));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        valor = Double.parseDouble(Dinero2.getText());
        calcula2(Menu.getSelector());
        Salida2.setText(valueOf(df.format(valor)));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void euDol(){
        MonedaEntrada1.setText("Euros");
        MonedaEntrada2.setText("Dolares");
        MonedaSalida1.setText("Dolares");
        MonedaSalida2.setText("Euros");
    }
    
    private void pColPArg(){
        MonedaEntrada1.setText("Pesos Colombianos");
        MonedaEntrada2.setText("Pesos Argentinos");
        MonedaSalida1.setText("Pesos Argentinos");
        MonedaSalida2.setText("Pesos Colombianos");
    }
    
    private void euPCol(){
        MonedaEntrada1.setText("Euros");
        MonedaEntrada2.setText("Pesos Colombianos");
        MonedaSalida1.setText("Pesos Colombianos");
        MonedaSalida2.setText("Euros");
    }
    
    private void pColDol(){
        MonedaEntrada1.setText("Pesos Colombianos");
        MonedaEntrada2.setText("Dolares");
        MonedaSalida1.setText("Dolares");
        MonedaSalida2.setText("Pesos Colombianos");
    }
    
    private void euPArg(){
        MonedaEntrada1.setText("Euros");
        MonedaEntrada2.setText("Pesos Argentinos");
        MonedaSalida1.setText("Pesos Argentinos");
        MonedaSalida2.setText("Euros");
    }
    private void pArgDol(){
        MonedaEntrada1.setText("Pesos Argentinos");
        MonedaEntrada2.setText("Dolares");
        MonedaSalida1.setText("Dolares");
        MonedaSalida2.setText("Pesos Argentinos");
    }
    
    public void setTextos(){
        switch(Menu.getSelector()){
            case 0: euDol();
                    break;
            case 1: pColPArg();
                    break;
            case 2: euPCol();
                    break;
            case 3: pColDol();
                    break;
            case 4: euPArg();
                    break;
            case 5: pArgDol();
                    break;
        }
    }
    
    private void calcula1(int selector){
        switch(selector){
            case 0: valor = valor*1.09428;
                    break;
            case 1: valor = (valor*15.40)/2919;
                    break;
            case 2: valor = valor*3084;
                    break;
            case 3: valor = valor/2919;
                    break;
            case 4: valor = valor*16.08;
                    break;
            case 5: valor = valor*15.40;
                    break;
        }
    }
    
    private void calcula2(int selector){
        switch(selector){
            case 0: valor = valor/1.09428;
                    break;
            case 1: valor = (valor*2919)/15.40;
                    break;
            case 2: valor = valor/3084;
                    break;
            case 3: valor = valor*2919;
                    break;
            case 4: valor = valor/16.08;
                    break;
            case 5: valor = valor/15.40;
                    break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField Dinero1;
    private javax.swing.JTextField Dinero2;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel MonedaEntrada1;
    private javax.swing.JLabel MonedaEntrada2;
    private javax.swing.JLabel MonedaSalida1;
    private javax.swing.JLabel MonedaSalida2;
    private javax.swing.JLabel Salida1;
    private javax.swing.JLabel Salida2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
