/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversor;

import java.awt.Color;

/**
 *
 * @author dalonsoperez
 */
public class Menu extends javax.swing.JFrame {

    private static int selector;
    Convertir obj = new Convertir();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit = new javax.swing.JButton();
        EuDol = new javax.swing.JButton();
        EuCol = new javax.swing.JButton();
        EuArg = new javax.swing.JButton();
        ColArg = new javax.swing.JButton();
        ColDol = new javax.swing.JButton();
        ArgDol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setBackground(new java.awt.Color(255, 0, 0));
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("x");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        EuDol.setText("€ - $");
        EuDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EuDolActionPerformed(evt);
            }
        });
        getContentPane().add(EuDol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        EuCol.setText("€ - $Col");
        EuCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EuColActionPerformed(evt);
            }
        });
        getContentPane().add(EuCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 110, -1));

        EuArg.setText("€ - $Arg");
        EuArg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EuArgActionPerformed(evt);
            }
        });
        getContentPane().add(EuArg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, -1));

        ColArg.setText("$Col - $Arg");
        ColArg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColArgActionPerformed(evt);
            }
        });
        getContentPane().add(ColArg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 110, -1));

        ColDol.setText("$Col - $");
        ColDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColDolActionPerformed(evt);
            }
        });
        getContentPane().add(ColDol, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 110, -1));

        ArgDol.setText("$Arg - $");
        ArgDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArgDolActionPerformed(evt);
            }
        });
        getContentPane().add(ArgDol, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void EuDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EuDolActionPerformed
        this.setVisible(false);
        obj.setVisible(true);
        selector = 0;
        obj.setTextos();
    }//GEN-LAST:event_EuDolActionPerformed

    private void ColArgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColArgActionPerformed
        this.setVisible(false);
        obj.setVisible(true);
        selector = 1;
        obj.setTextos();
    }//GEN-LAST:event_ColArgActionPerformed

    private void EuColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EuColActionPerformed
        this.setVisible(false);
        obj.setVisible(true);
        selector = 2;
        obj.setTextos();
    }//GEN-LAST:event_EuColActionPerformed

    private void ColDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColDolActionPerformed
        this.setVisible(false);
        obj.setVisible(true);
        selector = 3;
        obj.setTextos();
    }//GEN-LAST:event_ColDolActionPerformed

    private void EuArgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EuArgActionPerformed
        this.setVisible(false);
        obj.setVisible(true);
        selector = 4;
        obj.setTextos();
    }//GEN-LAST:event_EuArgActionPerformed

    private void ArgDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArgDolActionPerformed
        this.setVisible(false);
        obj.setVisible(true);
        selector = 5;
        obj.setTextos();
    }//GEN-LAST:event_ArgDolActionPerformed

    public static int getSelector(){
        return selector;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArgDol;
    private javax.swing.JButton ColArg;
    private javax.swing.JButton ColDol;
    private javax.swing.JButton EuArg;
    private javax.swing.JButton EuCol;
    private javax.swing.JButton EuDol;
    private javax.swing.JButton Exit;
    // End of variables declaration//GEN-END:variables
}
